from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

provenance_path = ROOT / "afuture" / "provenance.py"
provenance = provenance_path.read_text(encoding="utf-8")
start = provenance.index("def native_module_identity(")
new_native = '''def native_module_identity(package: str = "vnpy_ctp") -> dict[str, object] | None:\n    """Bind every native extension shipped by a package into one stable identity."""\n\n    try:\n        spec = importlib.util.find_spec(package)\n    except (ImportError, AttributeError, ValueError):\n        return None\n    if spec is None:\n        return None\n    candidates: list[Path] = []\n    suffixes = {".so", ".pyd", ".dylib"}\n    locations = list(spec.submodule_search_locations or ())\n    for raw_location in locations:\n        location = Path(raw_location)\n        try:\n            candidates.extend(\n                path\n                for path in location.rglob("*")\n                if path.is_file() and any(str(path).endswith(suffix) for suffix in suffixes)\n            )\n        except OSError:\n            continue\n    if not candidates and spec.origin and spec.origin not in {"built-in", "frozen"}:\n        origin = Path(spec.origin)\n        if any(str(origin).endswith(suffix) for suffix in suffixes):\n            candidates = [origin]\n    if not candidates:\n        return None\n\n    files: list[dict[str, str]] = []\n    seen: set[Path] = set()\n    for candidate in sorted(candidates, key=os.fspath):\n        target = canonical_safe_path(candidate, label="native module")\n        if target in seen:\n            continue\n        seen.add(target)\n        files.append({"path": str(target), "sha256": file_sha256(target)})\n    if not files:\n        return None\n    return {\n        "files": files,\n        "sha256": sha256(canonical_json_bytes(files)).hexdigest(),\n    }\n'''
provenance_path.write_text(provenance[:start] + new_native, encoding="utf-8")

backup_path = ROOT / "afuture" / "runtime_backup_impl.py"
backup = backup_path.read_text(encoding="utf-8")
marker = '''def restore_runtime(\n'''
insert_at = backup.index(marker)
helper = '''def _restore_incident_path(runtime: Path, incident_token: str) -> Path:\n    if not incident_token or any(character not in "0123456789abcdef" for character in incident_token):\n        raise RuntimeBackupError("restore incident token is invalid")\n    base = runtime.with_name(f".{runtime.name}.failed-restore-{incident_token}")\n    for index in range(1000):\n        candidate = base if index == 0 else base.with_name(f"{base.name}-{index}")\n        if not candidate.exists() and not candidate.is_symlink():\n            return candidate\n    raise RuntimeBackupError("restore incident namespace is exhausted")\n\n\ndef _quarantine_restore_runtime(runtime: Path, incident_token: str) -> Path:\n    incident = _restore_incident_path(runtime, incident_token)\n    try:\n        os.rename(runtime, incident)\n        _fsync_dir(runtime.parent)\n    except OSError as exc:\n        raise RuntimeBackupError("restore runtime quarantine failed") from exc\n    return incident\n\n\ndef _publish_restore_transaction(\n    *,\n    runtime_stage: Path,\n    runtime: Path,\n    stage_registry: Path,\n    registry: Path,\n    registry_stage_root: Path,\n    incident_token: str,\n) -> None:\n    """Publish runtime then registry; quarantine runtime if registry publication fails."""\n\n    if runtime.exists():\n        if not runtime.is_dir() or runtime.is_symlink() or any(runtime.iterdir()):\n            raise RuntimeBackupError("runtime became non-empty before atomic publish")\n        runtime.rmdir()\n        _fsync_dir(runtime.parent)\n    try:\n        os.rename(runtime_stage, runtime)\n        _fsync_dir(runtime.parent)\n    except OSError as exc:\n        raise RuntimeBackupError("restore runtime publication failed") from exc\n\n    try:\n        _publish_registry(stage_registry, registry)\n        if registry_stage_root.exists():\n            registry_stage_root.rmdir()\n            _fsync_dir(registry_stage_root.parent)\n    except Exception as exc:\n        try:\n            incident = _quarantine_restore_runtime(runtime, incident_token)\n        except RuntimeBackupError as quarantine_exc:\n            raise RuntimeBackupError(\n                "restore registry publication failed and canonical runtime quarantine failed"\n            ) from quarantine_exc\n        raise RuntimeBackupError(\n            f"restore registry publication failed; runtime quarantined at {incident}"\n        ) from exc\n\n\n'''
backup = backup[:insert_at] + helper + backup[insert_at:]
old_publish = '''        _publish_registry(stage_registry, registry)\n        if runtime.exists():\n            if any(runtime.iterdir()):\n                raise RuntimeBackupError("runtime became non-empty before atomic publish")\n            runtime.rmdir()\n            _fsync_dir(runtime.parent)\n        os.rename(runtime_stage, runtime)\n        runtime_published = True\n        _fsync_dir(runtime.parent)\n        registry_stage_root.rmdir()\n        _fsync_dir(registry_stage_root.parent)\n'''
new_publish = '''        _publish_restore_transaction(\n            runtime_stage=runtime_stage,\n            runtime=runtime,\n            stage_registry=stage_registry,\n            registry=registry,\n            registry_stage_root=registry_stage_root,\n            incident_token=verification.archive_sha256[:16],\n        )\n        runtime_published = True\n'''
if old_publish not in backup:
    raise SystemExit("restore publication block not found")
backup = backup.replace(old_publish, new_publish, 1)
old_except = '''    except Exception:\n        if not runtime_published and runtime_stage.exists():\n            shutil.rmtree(runtime_stage, ignore_errors=True)\n        raise\n'''
new_except = '''    except Exception:\n        if runtime_published and runtime.exists():\n            try:\n                _quarantine_restore_runtime(runtime, verification.archive_sha256[:16])\n            except RuntimeBackupError:\n                pass\n        elif runtime_stage.exists():\n            shutil.rmtree(runtime_stage, ignore_errors=True)\n        raise\n'''
if old_except not in backup:
    raise SystemExit("restore exception block not found")
backup = backup.replace(old_except, new_except, 1)
backup_path.write_text(backup, encoding="utf-8")
