from pathlib import Path

path = Path("afuture/stress90_operator_continuity.py")
text = path.read_text(encoding="utf-8")
old = '''        if current is not None:\n            if (\n                evidence.source_ctp_trading_day != current.evidence.target_ctp_trading_day\n                or evidence.source_trading_day_evidence_sequence\n                != current.target_trading_day_evidence_sequence\n                or evidence.source_trading_day_evidence_checksum\n                != current.target_trading_day_evidence_checksum\n                or evidence.source_account_registry_receipt_digest\n                != current.target_registry_receipt_digest\n            ):\n                raise Stress90OperatorContinuityError(\n                    "operator continuity source does not match the current receipt chain"\n                )\n'''
new = '''        if current is not None:\n            direct_continuation = bool(\n                evidence.source_ctp_trading_day == current.evidence.target_ctp_trading_day\n                and evidence.source_trading_day_evidence_sequence\n                == current.target_trading_day_evidence_sequence\n                and evidence.source_trading_day_evidence_checksum\n                == current.target_trading_day_evidence_checksum\n                and evidence.source_account_registry_receipt_digest\n                == current.target_registry_receipt_digest\n                and evidence.account_identity_digest\n                == current.evidence.account_identity_digest\n                and evidence.account_epoch == current.evidence.account_epoch\n                and evidence.canonical_runtime == current.evidence.canonical_runtime\n                and evidence.canonical_runtime_digest\n                == current.evidence.canonical_runtime_digest\n            )\n            same_account_rebase_reanchor = bool(\n                evidence.account_identity_digest\n                == current.evidence.account_identity_digest\n                and evidence.canonical_runtime == current.evidence.canonical_runtime\n                and evidence.canonical_runtime_digest\n                == current.evidence.canonical_runtime_digest\n                and evidence.account_epoch != current.evidence.account_epoch\n                and evidence.source_ctp_trading_day\n                >= current.evidence.target_ctp_trading_day\n                and evidence.source_trading_day_evidence_sequence\n                > current.target_trading_day_evidence_sequence\n                and evidence.source_trading_day_evidence_checksum\n                != current.target_trading_day_evidence_checksum\n                and evidence.source_account_registry_receipt_digest\n                != current.target_registry_receipt_digest\n                and evidence.source_generic_state_sequence\n                > current.evidence.source_generic_state_sequence\n                and evidence.source_policy_state_sequence\n                > current.evidence.source_policy_state_sequence\n            )\n            if not direct_continuation and not same_account_rebase_reanchor:\n                raise Stress90OperatorContinuityError(\n                    "operator continuity source does not match the current receipt chain or a "\n                    "verified same-account rebase reanchor"\n                )\n'''
if new not in text:
    if old not in text:
        raise SystemExit("operator continuity save chain anchor missing")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")
